print("Hello, world!")
print("nandini")
print("heyyy")
print("what you doing?")
print(2+3)
print(10/2)
print(9//2)
print(10%3)
print(2**4)
print(10.2*3)
name = input("What's your name?") 
print("Nice to meet you",name) 
name = input("What's your name?")
name = input("What is your name? ")
print("Hello, " + name + "!")
name = input("What's your name?") 
print("Nice to meet you", name)
age = int(input("Enter your age: "))
print("In 5 years, you'll be", age + 5)
name = input("Which city do you live in?") 
print("I would love to visit", name)  
print("Ohhh!!"+ name + " is a beautiful city.")
age = int(input("What's your age?"))
print("in next 2 years, you'll be", age+2)
print("Ribhav's age is", age/2)
print("age in months is", age *12)
print("Welcome to simple calculator.")
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Quotient:", a / b)
print(a%b)
print(a**b)
results = ("23.0", "-3.0", "130.0", "0.769230769", "10.0", "10000000000000.0")
print("".join(results)) 
